### ISSUE TITLE
bug(vmware_vcd) connection problems result in not enought data being collected

### ISSUE THREAD

**Issue by samsk** [promitilus/cloudinventario#80]
There are weird connection problem to some services what results with either complete collection fail, or (what is worse) only partial data collection.
The problem seems to be here https://github.com/promitilus/cloudinventario/blob/master/src/cloudinventario_vmware_vcd/collector.py#L121

It should only catch VMWare (pyvcloud.vcd) related errors, not HTTP connection problems or similar - they should be rethrown.

```
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f5de16e12e0>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='vdc.iaas.orange.ro', port=443): Max retries exceeded with url: /api/org/b7812c69-5d5d-4f14-b023-86d8408c0008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5de16e12e0>: Failed to establish a new connection: [Errno 113] No route to host'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/./cloudinventario", line 61, in collect
    inventory = cinv.collect(name, options)
  File "/app/src/cloudinventario/cloudinventario.py", line 64, in collect
    instance.login()
  File "/app/src/cloudinventario/helpers.py", line 53, in login
    session = self._login()
  File "/app/src/cloudinventario_vmware_vcd/collector.py", line 57, in _login
    org_res = self.client.get_org()
  File "/usr/local/lib/python3.9/site-packages/pyvcloud/vcd/client.py", line 1608, in get_org
    return self._get_wk_resource(_WellKnownEndpoint.LOGGED_IN_ORG)
  File "/usr/local/lib/python3.9/site-packages/pyvcloud/vcd/client.py", line 1752, in _get_wk_resource
    return self.get_resource(self._get_wk_endpoint(wk_type))
  File "/usr/local/lib/python3.9/site-packages/pyvcloud/vcd/client.py", line 1541, in get_resource
    return self._do_request(
  File "/usr/local/lib/python3.9/site-packages/pyvcloud/vcd/client.py", line 1242, in _do_request
    response = self._do_request_prim(
  File "/usr/local/lib/python3.9/site-packages/pyvcloud/vcd/client.py", line 1382, in _do_request_prim
    response = session.request(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vdc.iaas.orange.ro', port=443): Max retries exceeded with url: /api/org/b7812c69-5d5d-4f14-b023-86d8408c0008 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5de16e12e0>: Failed to establish a new connection: [Errno 113] No route to host'))
```

**Comment by samsk** [comment]
The same here https://github.com/promitilus/cloudinventario/blob/master/src/cloudinventario_vmware_vcd/collector.py#L228
