### ISSUE TITLE
bug(amazon_aws) import problems

### ISSUE THREAD

**Issue by samsk** [promitilus/cloudinventario#93]
2022-07-05 05:33:48|sb-cloud-ops|7|ERROR|Traceback (most recent call last):
  File "/app/./cloudinventario", line 68, in collect
    inventory = cinv.collect(name, options)
  File "/app/src/cloudinventario/cloudinventario.py", line 83, in collect
    instance = self.loadCollector(collector, options)
  File "/app/src/cloudinventario/cloudinventario.py", line 38, in loadCollector
    return CloudInventario.loadCollectorModule(mod_name, collector, mod_config, mod_defaults, options)
  File "/app/src/cloudinventario/cloudinventario.py", line 47, in loadCollectorModule
    mod = importlib.import_module(mod_pkg + '.collector')
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/src/cloudinventario_amazon_aws_multi/collector.py", line 12, in <module>
    from cloudinventario_amazon_aws_resource import CloudInvetarioAmazonAWSResource
ImportError: cannot import name 'CloudInvetarioAmazonAWSResource' from 'cloudinventario_amazon_aws_resource' (/app/src/cloudinventario_amazon_aws_resource/__init__.py)

**Comment by samsk** [comment]
Not fixed

```2022-07-07 07:33:49,257 [sb-cloud-ops] [DEBUG] Importing module: cloudinventario_amazon_aws_multi.resources.rds
2022-07-07 07:33:49,258 [sb-cloud-ops] [ERROR] Failed to load the following module:cloudinventario_amazon_aws_multi.resources.rds, reason: No module named 'cloudinventario_amazon_aws_multi.resources'
2022-07-07 07:33:49,259 [sb-cloud-ops] [DEBUG] Importing module: cloudinventario_amazon_aws_multi.resources.snapshot
2022-07-07 07:33:49,259 [sb-cloud-ops] [ERROR] Failed to load the following module:cloudinventario_amazon_aws_multi.resources.snapshot, reason: No module named 'cloudinventario_amazon_aws_multi.resources'
2022-07-07 07:33:49,259 [sb-cloud-ops] [DEBUG] Importing module: cloudinventario_amazon_aws_multi.resources.ebs
2022-07-07 07:33:49,260 [sb-cloud-ops] [ERROR] Failed to load the following module:cloudinventario_amazon_aws_multi.resources.ebs, reason: No module named 'cloudinventario_amazon_aws_multi.resources'
2022-07-07 07:33:49,260 [sb-cloud-ops] [DEBUG] Importing module: cloudinventario_amazon_aws_multi.resources.s3
2022-07-07 07:33:49,261 [sb-cloud-ops] [ERROR] Failed to load the following module:cloudinventario_amazon_aws_multi.resources.s3, reason: No module named 'cloudinventario_amazon_aws_multi.resources'```
